spring.application.name=ms-reportes
server.port=8091

# Base de datos exclusiva del microservicio de reportes
spring.datasource.url=jdbc:mysql://localhost:3307/bbdd_reportes?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=reportes123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.open-in-view=false

# JWT - mismo secret que ms-usuarios para validar tokens
jwt.secret=TXlTdXBlclNlY3JldEtleUZvck51YmVDb21pY3NKV1QyMDI1
jwt.expiration=86400000

logging.level.BookHub.msreportes=INFO
